name: Report for lab 1

on:
  push:
    branches: [ master ]
    paths:
      - 'lab1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build pdf from report.ipynb
        id: build
        uses: Mervap/IpynbToPDFAction@v1.0.0
        with:
          ipynb-path: 'lab1/report.ipynb'
          pdf-name: 'report'
          template-path: 'russian_template.tex.j2'
      - name: Move report
        run: |
          rm out/report1.pdf
          cp report.pdf out/report1.pdf
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: out